global_frame: map
robot_base_frame: footprint
always_send_full_costmap: true


transform_tolerance: 0.5
footprint: [[-0.38, -0.18], [-0.38, 0.18], [0.06, 0.18], [0.06, -0.18]]
footprint_padding: 0.05
map_type: costmap
# subscribe_to_updates: true

inflation_layer:
  inflation_radius: 1.0
  cost_scaling_factor: 30

obstacle_layer:
  obstacle_range: 4.5
  raytrace_range: 5.0
  inflation_radius: 0.1
  # observation_persistence: 0.0
  track_unknown_space: true
  observation_sources: scan_laser
  scan_laser: 
    sensor_frame: laser
    data_type: LaserScan
    topic: /filtered_scan
    marking: true
    clearing: true

static_layer:
  enabled:              true
  map_topic:            "/map"
#  lethal_cost_threshold: 70
#  static_map: true
#  track_unknown_space: false
#  unknown_cost_value: 1
#  trinary_costmap: false
#  use_maximum: true



#rgbd_obstacle_layer:
#  obstacle_range: 2.5
#  raytrace_range: 5.5
#  publish_voxel_map: True
#  observation_sources: front_rgbd_to_scan
#  front_rgbd_to_scan:
#    data_type: PointCloud2
#    topic: /camera/depth/points
#    marking: True
#    clearing: True
#    voxel_filter: true






