global_costmap:
  global_frame: map
  robot_base_frame: footprint
  update_frequency: 1.0
  publish_frequency: 0.5

  static_map: true
  rolling_window: false
  resolution: 0.1
  # inflation_radius: 5.0
  cost_scaling_factor: 10
  robot_radius: 0.35

  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"} 
    # - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,      type: "costmap_2d::InflationLayer"}
  
 



