local_costmap:
  global_frame: odom
  # global_frame: odom_combined
  robot_base_frame: footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 5.5
  height: 5.5
  resolution: 0.1
  transform_tolerance: 0.5
#  footprint_padding: 0.0
#  inflation_radius: 5.0
  cost_scaling_factor: 25
  # robot_radius: 0.2
  # inflation_radius: 5.0

  
  
  plugins:
    # - 
    #   name: obstacle_layer
    #   type: "costmap_2d::VoxelLayer"
    # # - 
    # #   name: static_layer
    # #   type: "costmap_2d::StaticLayer"
    # - 
    #   name: inflation_layer
    #   type: "costmap_2d::InflationLayer"
  #  - {name: static_layer,        type: "costmap_2d::StaticLayer"} 
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,      type: "costmap_2d::InflationLayer"}
    


